version: '3'
services:
  mongodb:
    container_name: mongo-db
    image: mongo:latest
    networks:
      mongo-network:
        ipv4_address: 198.168.115.2
    ports:
    - "27017:27017"
    extra_hosts:
    - "__MONGODB__:127.0.0.1"
    volumes:
    - ./docker/mongo-data/:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
networks:
  mongo-network:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 198.168.115.0/24